In [0]:
import numpy as np
from scipy import stats

<h3> Задача1</h3>
<p>  Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.
Даны значения роста в трех группах случайно выбранных спортсменов: <ul>
<li> Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. </li>
<li> Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. </li>
<li> Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.</li> </ul></p>

In [0]:
#объявим массивы для хранения данных
footBall = np.array([173, 175, 180, 178, 177, 185, 183, 182])
iceHockey = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
weightLifting = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
print(footBall, '\n', iceHockey, '\n', weightLifting)                               

[173 175 180 178 177 185 183 182] 
 [177 179 180 188 177 172 171 184 180] 
 [172 173 169 177 166 180 178 177 172 166 170]


In [0]:
# Выполним однофакторный дисперсионный анализ
alpha = 0.05 # уровень значимости
df1 = 3-1 # Cтепень свободы числителя к-1, k - число групп
df2 = sum([len(footBall), len(iceHockey), len(weightLifting)]) - 3 # степень свободы знаменатля
f_cr = stats.f.ppf(1-alpha, df1,df2)

st, p_val = stats.f_oneway(footBall, iceHockey, weightLifting)
print(f"Степень свободы числителя {df1}, \n степень свободы знаменателя {df2}, \n Критеческое значение F-критерия {f_cr}")
if st > f_cr:
    print (f"""Значение расчетного критерия {st} больше критического {f_cr}, следовательно между ростом спортсменов, 
    занимающихся разными видами спорта имеются значимые различия""")
else:
    print(f"""Значение расчетного критерия {st} меньше критического {f_cr}, следовательно между ростом спортсменов, 
    занимающихся разными видами спорта не имеется значимых различий""")

Степень свободы числителя 2, 
 степень свободы знаменателя 25, 
 Критеческое значение F-критерия 3.3851899614491687
Значение расчетного критерия 5.500053450812596 больше критического 3.3851899614491687, следовательно между ростом спортсменов, 
    занимающихся разными видами спорта имеются значимые различия
